import { DEFAULT_PLAYER_RIG } from './player_default_rig_data.js';
import { defaultTimelineModifiers } from './timeline_modifier_data.js';

export const DEFAULT_PLAYER_TUNING = {
  maxHpPips: 5,
  speed: 0,
  runAcceleration: 0,
  jumpPower: 0,
  airFlapPower: 0,
  airFlapCooldown: 0,
  glideTimeMax: 0,
  glideFallSpeed: 0,
  dashCooldownMax: 0,
  attackCooldownMax: 0,
  comboResetTime: 0,
  invulnerability: { hurt: 0, rollEnd: 0 },
  transform: { scale: 1, anchorX: 0, anchorY: 0 },
  hud: { offsetY: 0 },
  effects: { hitShake: 1.6, hitSpark: 1 },
  customActions: [],
  deletedActionKeys: [],
  actionNames: {},
  actionTriggers: {},
  modifiers: defaultTimelineModifiers(),
  effectOffsets: {
    idle: {},
    run: {},
    jump: {},
    fall: {},
    glide: {},
    roll: {},
    guard: {},
    guardBreak: {},
    hurt: {},
    death: {},
    jumpAttack: { image: 'slash2' },
    attack1: { image: 'slash1' },
    attack2: { image: 'slash2' },
    attack3: { image: 'slash3' },
  },
  effectSettings: {
    idle: { duration: 0.8, playback: 'loop', playbackRate: 1, mirror: true },
    run: { duration: 0.58, playback: 'loop', playbackRate: 1, mirror: true },
    jump: { duration: 0.42, playback: 'once', playbackRate: 1, mirror: true },
    fall: { duration: 0.55, playback: 'loop', playbackRate: 1, mirror: true },
    glide: { duration: 0.8, playback: 'loop', playbackRate: 1, mirror: true },
    roll: { duration: 0.28, playback: 'once', playbackRate: 1, mirror: true },
    guard: { duration: 0.35, playback: 'loop', playbackRate: 1, mirror: true },
    guardBreak: { duration: 0.38, playback: 'once', playbackRate: 1, mirror: true },
    hurt: { duration: 0.24, playback: 'once', playbackRate: 1, mirror: true },
    death: { duration: 1.1, playback: 'once', playbackRate: 1, mirror: true },
    jumpAttack: { duration: 0.34, playback: 'once', playbackRate: 1, mirror: true },
    attack1: { duration: 0.26, playback: 'once', playbackRate: 1, mirror: true },
    attack2: { duration: 0.28, playback: 'once', playbackRate: 1, mirror: true },
    attack3: { duration: 0.36, playback: 'once', playbackRate: 1, mirror: true },
  },
  motion: {},
  layerOrder: ['leftLeg', 'body', 'head', 'cape', 'leftArm', 'rightLeg', 'rightArm', 'shield', 'weapon'],
  actionOffsets: {
    idle: {},
    run: {},
    jump: {},
    fall: {},
    glide: {},
    roll: {},
    guard: {},
    guardBreak: {},
    hurt: {},
    death: {},
    jumpAttack: {},
    attack1: {},
    attack2: {},
    attack3: {},
  },
  actionSettings: {
    idle: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    run: { duration: 0.58, playback: 'loop', playbackRate: 1 },
    jump: { duration: 0.42, playback: 'once', playbackRate: 1 },
    fall: { duration: 0.55, playback: 'loop', playbackRate: 1 },
    glide: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    roll: { duration: 0.28, playback: 'once', playbackRate: 1 },
    guard: { duration: 0.35, playback: 'loop', playbackRate: 1 },
    guardBreak: { duration: 0.38, playback: 'once', playbackRate: 1 },
    hurt: { duration: 0.24, playback: 'once', playbackRate: 1 },
    death: { duration: 1.1, playback: 'once', playbackRate: 1 },
    jumpAttack: { duration: 0.34, playback: 'once', playbackRate: 1 },
    attack1: { duration: 0.26, playback: 'once', playbackRate: 1 },
    attack2: { duration: 0.28, playback: 'once', playbackRate: 1 },
    attack3: { duration: 0.36, playback: 'once', playbackRate: 1 },
  },
  rig: DEFAULT_PLAYER_RIG,
};
