import { DEFAULT_PLAYER_RIG } from './playerDefaultRig.js';

export const DEFAULT_PLAYER_TUNING = {
  maxHpPips: 5,
  speed: 260,
  jumpPower: 690,
  airFlapPower: 185,
  airFlapCooldown: 0.1,
  jumpHoldMax: 0.16,
  jumpHoldForce: 620,
  glideTimeMax: 1.1,
  glideFallSpeed: 180,
  dashDuration: 0.28,
  rollDistance: 240,
  dashCooldownMax: 0.45,
  attackCooldownMax: 0.18,
  comboResetTime: 0.72,
  invulnerability: { hurt: 0.45, rollEnd: 0.18 },
  transform: { scale: 1, anchorX: 0, anchorY: 0 },
  hitbox: { x: -24, y: -112, w: 48, h: 112 },
  attackBox: { frontX: 26, backX: -96, y: -92, w: 70, h: 50 },
  attackBoxes: {
    attack1: {
      x: 8,
      y: -12,
      w: 96,
      h: 28,
      rot: 0,
      frontX: 26,
      backX: -96,
      stun: 0.22,
      knockbackX: 330,
      knockbackY: 110,
      deathBurst: 1,
    },
    attack2: {
      x: 8,
      y: -13,
      w: 108,
      h: 30,
      rot: 0,
      flipX: true,
      frontX: 18,
      backX: -88,
      stun: 0.22,
      knockbackX: 380,
      knockbackY: 120,
      deathBurst: 1.08,
    },
    attack3: {
      x: 6,
      y: -15,
      w: 124,
      h: 34,
      rot: 0,
      frontX: 22,
      backX: -116,
      stun: 0.28,
      knockbackX: 520,
      knockbackY: 190,
      deathBurst: 1.28,
    },
    jumpAttack: {
      x: 6,
      y: -14,
      w: 104,
      h: 32,
      rot: 0,
      frontX: -36,
      backX: -34,
      stun: 0.26,
      knockbackX: 220,
      knockbackY: 260,
      deathBurst: 1.18,
    },
  },
  effects: { hitShake: 1.6, hitSpark: 1 },
  effectOffsets: {
    idle: {},
    run: {},
    jump: {},
    fall: {},
    glide: {},
    roll: {},
    guard: {},
    guardBreak: {},
    hurt: {},
    death: {},
    jumpAttack: { image: 'slash2' },
    attack1: { image: 'slash1' },
    attack2: { image: 'slash2' },
    attack3: { image: 'slash3' },
  },
  effectSettings: {
    idle: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    run: { duration: 0.58, playback: 'loop', playbackRate: 1 },
    jump: { duration: 0.42, playback: 'once', playbackRate: 1 },
    fall: { duration: 0.55, playback: 'loop', playbackRate: 1 },
    glide: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    roll: { duration: 0.28, playback: 'once', playbackRate: 1 },
    guard: { duration: 0.35, playback: 'loop', playbackRate: 1 },
    guardBreak: { duration: 0.38, playback: 'once', playbackRate: 1 },
    hurt: { duration: 0.24, playback: 'once', playbackRate: 1 },
    death: { duration: 1.1, playback: 'once', playbackRate: 1 },
    jumpAttack: { duration: 0.34, playback: 'once', playbackRate: 1 },
    attack1: { duration: 0.26, playback: 'once', playbackRate: 1 },
    attack2: { duration: 0.28, playback: 'once', playbackRate: 1 },
    attack3: { duration: 0.36, playback: 'once', playbackRate: 1 },
  },
  hitReaction: {
    stun: 0.22,
    knockbackX: 330,
    knockbackY: 110,
    heavyKnockbackX: 520,
    heavyKnockbackY: 190,
  },
  motion: {
    animationIntensity: {
      idle: 1,
      run: 1,
      jump: 1,
      fall: 1,
      glide: 1,
      roll: 1,
      guard: 1,
      guardBreak: 1,
      hurt: 1,
      death: 1,
      jumpAttack: 1,
      attack1: 1,
      attack2: 1,
      attack3: 1,
    },
    walkSpeed: 12,
    walkBob: 5,
    walkBody: 4,
    walkArmSwing: 34,
    walkLegSwing: 38,
    jumpRiseGravity: 0.55,
    jumpRiseEase: 2.2,
    dashLean: 18,
    rollSpin: 360,
    rollTuck: 52,
    rollLift: 18,
  },
  layerOrder: ['leftLeg', 'body', 'head', 'cape', 'leftArm', 'rightLeg', 'rightArm', 'shield'],
  poseOffsets: {
    idle: {},
    run: {},
    jump: {},
    fall: {},
    glide: {},
    roll: {},
    guard: {},
    guardBreak: {},
    hurt: {},
    death: {},
    jumpAttack: {},
    attack1: {},
    attack2: {},
    attack3: {},
  },
  poseSettings: {
    idle: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    run: { duration: 0.58, playback: 'loop', playbackRate: 1 },
    jump: { duration: 0.42, playback: 'once', playbackRate: 1 },
    fall: { duration: 0.55, playback: 'loop', playbackRate: 1 },
    glide: { duration: 0.8, playback: 'loop', playbackRate: 1 },
    roll: { duration: 0.28, playback: 'once', playbackRate: 1 },
    guard: { duration: 0.35, playback: 'loop', playbackRate: 1 },
    guardBreak: { duration: 0.38, playback: 'once', playbackRate: 1 },
    hurt: { duration: 0.24, playback: 'once', playbackRate: 1 },
    death: { duration: 1.1, playback: 'once', playbackRate: 1 },
    jumpAttack: { duration: 0.34, playback: 'once', playbackRate: 1 },
    attack1: { duration: 0.26, playback: 'once', playbackRate: 1 },
    attack2: { duration: 0.28, playback: 'once', playbackRate: 1 },
    attack3: { duration: 0.36, playback: 'once', playbackRate: 1 },
  },
  rig: DEFAULT_PLAYER_RIG,
};
